# Generated by Django 4.0.6 on 2022-07-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_trendy',
            field=models.BooleanField(default=False),
        ),
    ]
