# Generated by Django 4.0.6 on 2022-07-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
