# Generated by Django 4.0.6 on 2022-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
