# Generated by Django 4.0.6 on 2022-07-18 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book', '0011_favorite_book_favorite_favorite_book_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_book_user', through='book.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
