# Generated by Django 4.0.6 on 2022-07-18 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book', '0012_alter_book_favorite_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorite',
            field=models.ManyToManyField(related_name='book_user', through='book.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
